on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Vulnerability Scan
        run: |
          gem install bundler-audit
          bundler-audit --update && bundler-audit check

      - name: Unit Tests
        run: bundle exec rspec

      - name: Login to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image (develop)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop .
          docker push ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop
